### ISSUE TITLE
Cloudflare API Error - Authentication error

### ISSUE THREAD

**Issue by szkbury** [cloudflare/origin-ca-issuer#108]
Hi,

Today I saw I am getting the following errors on origin-ca-issuer.

`
{"level":"error","error":"unable to sign request: Cloudflare API Error code=10000 message=Authentication error","name":"origin-issuer/controllers/CertificateRequest","certificaterequest":{"Namespace":"kube-system","Name":"[masked]-ai-tjt7p"},"time":"2024-01-15T15:33:33Z","message":"failed to sign certificate request"}
{"level":"error","error":"unable to sign request: Cloudflare API Error code=10000 message=Authentication error","name":"controller","reconcilerGroup":"cert-manager.io","reconcilerKind":"CertificateRequest","controller":"certificaterequest","name":"[masked]-ai-tjt7p","namespace":"kube-system","time":"2024-01-15T15:33:33Z","message":"Reconciler error"}
`

nothing changed on my side. API token was double-checked and it is ok.

I saw #105 - does it mean that something is wrong with CloudFlare API?

**Comment by terinjokes** [comment]
What version of origin-ca-issuer? Is the certificate for a domain on the same account?

**Comment by szkbury** [comment]
cloudflare/origin-ca-issuer:v0.6.1

yes this is the same account.

I want to add that it was working with the same configuration for more than a year so far, and suddenly stopped...

**Comment by terinjokes** [comment]
I'm not sure why it would have stopped working, and unfortunately the error message is the most generic.

Can you rotate the Origin CA API token secret, then restart the origin-ca-issuer pod(s), and then use the cert-manager CLI to start a [renewal manually](https://cert-manager.io/docs/reference/cmctl/#renew)?

**Comment by shmuelarditi** [comment]
@terinjokes i have a similar problem, although im a new installer and i implemented it today in my company for the first time, im getting this error:

```
{"level":"error","error":"unable to sign request: Cloudflare API Error code=10000 message=Authentication error","name":"controller","reconcilerGroup":"cert-manager.io","reconcilerKind":"CertificateRequest","controller":"certificaterequ │││ est","name":"elementor-red-internal-origin-certificate-hpvbh","namespace":"cert-manager","time":"2024-01-15T15:43:24Z","message":"Reconciler error"} 
```

provided the issuer a secret holding an API KEY from our main devops account that has permissions to all zone, 
gave the key the permission Zone --> SSL and Certificate, on all zones.

**Comment by terinjokes** [comment]
@shmuelarditi As noted in the readme, it has to be the “Origin CA Key” API key. You can't use a normal API key with origin-ca-issuer.

**Comment by shmuelarditi** [comment]
> @shmuelarditi As noted in the readme, it has to be the “Origin CA Key” API key. You can't use a normal API key with origin-ca-issuer.

@terinjokes King! it worked :), thank you for the fast comment

**Comment by szkbury** [comment]
it fixed the issue in my case as well but how it is possible it stopped working?

**Comment by terinjokes** [comment]
@szkbury which part of this thread fixed your issue?

**Comment by szkbury** [comment]
https://github.com/cloudflare/origin-ca-issuer/issues/108#issuecomment-1892427131

**Comment by terinjokes** [comment]
I understand why the restarts were neccessary after updating the secret (a bug I will fix), but I'm not sure why a token stopped working in the first place.

**Comment by shanehughes1990** [comment]
I also had this issue since about this time yesterday, basically all up coming certs had this issue and no changes what so ever.

I did end up rotating my credentials on cloud flare myself and restarting the origin issuer ca container yesterday before I ever saw this issue, but it has still been happing to a couple of renews today after the fact where I had to restart the issuer again to resolve.

I did notice some things this morning with k8s itself

I got alerted one of my DNS uptime checks were not passing
went to the page got the cloud flare err page where host is not available (first/second dots are green the host is a red x)
Checked on the certificate in cluster k8s reported the certificate as true on the `kubectl get certificate` output
Describing the certificate I have an attached event on it with the 10000 auth error.

I was able to renew it by restarting the issuer ca pod and deleting the certificate in question and it came back just fine.

**Comment by shanehughes1990** [comment]
@terinjokes just got another notification for one
```yaml
Status:
  Conditions:
    Last Transition Time:    2023-09-18T19:23:10Z
    Message:                 Certificate is up to date and has not expired
    Observed Generation:     1
    Reason:                  Ready
    Status:                  True
    Type:                    Ready
    Last Transition Time:    2024-01-14T16:18:00Z
    Message:                 The certificate request has failed to complete and will be retried: Failed to sign certificate request: unable to sign request: Cloudflare API Error code=10000 message=Authentication error
    Observed Generation:     1
    Reason:                  Failed
    Status:                  False
    Type:                    Issuing
  Failed Issuance Attempts:  6
  Last Failure Time:         2024-01-14T16:18:00Z
  Not After:                 2024-01-15T17:18:00Z
  Not Before:                2024-01-08T17:18:00Z
  Renewal Time:              2024-01-13T09:18:00Z
  Revision:                  25
Events:                      <none>
```

Latest logs from origin issuer for the relevant certificate
```sh
{"level":"debug","verbosity":4,"name":"origin-issuer/controllers/CertificateRequest","certificaterequest":{"Namespace":"apps","Name":"OBFUSCATED"},"time":"2024-01-15T13:49:02Z","message":"CertificateRequest is Ready. Ignoring."}
{"level":"info","verbosity":1,"name":"controller","reconcilerGroup":"cert-manager.io","reconcilerKind":"CertificateRequest","controller":"certificaterequest","name":"OBFUSCATED","namespace":"apps","time":"2024-01-15T13:49:02Z","message":"Successfully Reconciled"}
```

All 52 entries I have since restart today for this certificate all say the same.
