### ISSUE TITLE
[BUG] unknown flag: --cluster-resource-namespace

### ISSUE THREAD

**Issue by markusheinemann** [cloudflare/origin-ca-issuer#126]
# Description
I have deployed origin-ca-issuer using the resources from this repository.

On startup the pod is failing with the given error message:

```
unknown flag: --cluster-resource-namespace
Usage of /bin/controller:
      --disable-approved-check   Disables waiting for CertificateRequests to have an approved condition before signing.
      --kube-api-burst int       Maximium queries-per-second burst of request send to the Kubernetes apiserver. (default 50)
      --kube-api-qps float32     Maximium queries-per-second of requests to the Kubernetes apiserver. (default 20)
```

# Reproducing 
I can easily reproducing this bug running the container image locally with docker:

```
 docker run cloudflare/origin-ca-issuer:v0.8.0 --cluster-resource-namespace=origin-ca-issuer
```

# Workaround

I can workaround this error patching the deployment args using kustomize:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # CRDs
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
  # RBAC
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/rbac/role.yaml
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/rbac/role-approver.yaml
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/rbac/role-binding.yaml
  # Resources
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/manifests/0-namespace.yaml
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/manifests/deployment.yaml
  - https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/trunk/deploy/manifests/serviceaccount.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: []
    target:
      group: apps
      version: v1
      kind: Deployment
      name: origin-ca-issuer
```
