### ISSUE TITLE
Origin CA Issuer rejects rather than ignores CertificateRequests with a missing spec.issuerRef.group

### ISSUE THREAD

**Issue by KingJ** [cloudflare/origin-ca-issuer#149]
We recently upgraded Origin CA Issuer from v0.8.0 to v0.9.0 in our lab environment. Following this, a number of Cert Manager `Certificate` objects have failed to issue. The `CertificateRequest` for these certificates contains the following status condition;

```
    - lastTransitionTime: '2024-11-01T09:23:52Z'
      message: 'Unknown issuer kind: Issuer'
      reason: Failed
      status: 'False'
      type: Ready
```

The `Certificate` and the associated `Issuer` are rather bare-bones. The following manifest was used to replicate the issue;

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  dnsNames:
    - capi-operator-webhook-service.capi-operator-system.svc
    - capi-operator-webhook-service.capi-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: test-selfsigned-issuer
  secretName: test-cert
```

If the `Certificate`'s `spec.issuerRef.group` is subsequently set to `cert-manager.io`, then the certificate is issued successfully. Setting the group is optional when using one of Cert Manager's own internal issuers - it only needs to be set for external issues like the Origin CA Issuer.

While troubleshooting this issue with Cert Manager's developers, we discovered that it was not Cert Manager's own internal self-signed issuer that was returning this error - but the Origin CA Issuer. From the Origin CA Issuer logs;

```
{"level":"error","namespace":"default","certificaterequest":"test-cert-1","error":"unknown issuer kind: Issuer","logger":"origin-issuer/controllers/CertificateRequest","namespace":"default","name":"test-cert-1","caller":"/go/src/app/pkgs/controllers/certificaterequest.go:175","time":1730458599171,"message":"certificate request references unknown issuer kind"}
{"level":"error","controller":"certificaterequest","controllerGroup":"cert-manager.io","controllerKind":"CertificateRequest","CertificateRequest":{"name":"test-cert-1","namespace":"default"},"namespace":"default","name":"test-cert-1","reconcileID":"4ddcbbb2-c258-4202-ac40-8e45d5454bbb","error":"unknown issuer kind: Issuer","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:329","time":1730458599191,"message":"Reconciler error"}
```

As issuers are expected to process `CertificateRequests` in parallel, Cert Manager will only accept the first response back from an issuer. Issuers are expected to ignore `CertificateRequests` that do not relate to them - however, the Origin CA Issuer handles the `CertificateRequest` generated from the `Certificate` above and rejects it - therefore if Cert Manager's own internal self-signed issuer responds slower than the Origin CA Issuer, the Certificate will not be issued successfully.

Setting the `Certificate`'s `spec.issuerRef.group` is subsequently set to `cert-manager.io` bypasses this issue, as the Origin CA Issuer correctly ignores the `CertificateRequest` - it is only when `spec.issuerRef.group` is unset (which is valid) that the Origin CA Issuer incorrectly handles the `CertificateRequest` and thus returns an error.

Origin CA Issuer should be fixed to perform a more explicit check on `spec.issuerRef` - and only handle requests where the `group` is explicitly set to `cert-manager.k8s.cloudflare.com`.
