### ISSUE TITLE
Cloudflare API Error code=10000 only with Cluster Issuer

### ISSUE THREAD

**Issue by philthynz** [cloudflare/origin-ca-issuer#159]
I am getting error `Cloudflare API Error code=10000` only when using Cluster Issuer. OriginIssuer seems to work fine for my test application "aspnet".

Used version and config:

origin-ca-issuer crds version: v0.11.0
origin-ca-issuer helm chart version: 0.5.11
test helm chart: oci://registry-1.docker.io/bitnamicharts/aspnet-core
k8s version: v1.31.3+k3s1
cluster issuer config:
```
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: prod-cluster-issuer
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cfapi-token
      key: CloudflareAPIToken
```
ca token secret:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cfapi-token
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: cfapi-token
    creationPolicy: Owner
  data:
    - secretKey: CloudflareAPIToken
      remoteRef:
        key: CloudflareAPIKey
```

When specifying an ingress resource with these annotations:

```
      cert-manager.io/issuer: "prod-cluster-issuer",
      cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com,
      cert-manager.io/issuer-kind: ClusterOriginIssuer,
```

The origin-ca-issuer pod has the following errors:

```
{"level":"error","namespace":"aspnet","certificaterequest":"aspnet.whitecomputing.com-tls-1","error":"unable to sign request: Cloudflare API Error code=10000 message=Authentication error ray_id=8fc102832935a7ed-SYD","logger":"origin-issuer/controllers/CertificateRequest","caller":"/go/src/app/pkgs/controllers/certificaterequest.go:262","time":1735886556857,"message":"failed to sign certificate request"}
{"level":"error","controller":"certificaterequest","controllerGroup":"cert-manager.io","controllerKind":"CertificateRequest","CertificateRequest":{"name":"aspnet.whitecomputing.com-tls-1","namespace":"aspnet"},"namespace":"aspnet","name":"aspnet.whitecomputing.com-tls-1","reconcileID":"ebaa0f76-bcaa-4ecf-a19f-02f80571d83b","error":"unable to sign request: Cloudflare API Error code=10000 message=Authentication error ray_id=8fc102832935a7ed-SYD","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316","time":1735886556906,"message":"Reconciler error"}
```

I have rotated my `Origin CA Key` and restarted the `origin-ca-issuer` pod and still no luck.

Anything I am missing?
