### ISSUE TITLE
OOMkill pod memory limits

### ISSUE THREAD

**Issue by matthewdaltonditto** [cloudflare/origin-ca-issuer#23]
Pod memory limits seem a little low, had to bump in my cluster to get the pods to come up. or else they were crashing on startup running out of memory

**Comment by terinjokes** [comment]
Ok cool, fortunately that's an easy change. Does your cluster have a large amount of cert-manger certificates or secrets?

**Comment by xunholy** [comment]
I had the same issue initially with the `v0.5.1` image, you're going to get a `OOMKilled` but the solution is the increase the limit, for me increasing the limits for memory to `100Mi` was sufficent.

```
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi
```
