### ISSUE TITLE
Feature: ClusterOriginIssuer support or cross namespace referencing

### ISSUE THREAD

**Issue by xunholy** [cloudflare/origin-ca-issuer#24]
A feature I'd like to see is to be able to create a cluster scoped ClusterOriginIssuer resource that my `Certificates` can reference. 

At present the `OriginIssuer` seems to need to be present in the same namespace that the `Certificate` is located in.

For example, I'm using istio and running my `ingress-gateway` in the `istio-system` namespace, therefore i'm going to create my `Certificate` resource in this namespace, however, I've deployed origin-ca-issuer with the `OriginIssuer` into my `network` namespace.

```
{"level":"error","error":"OriginIssuer.cert-manager.k8s.cloudflare.com \"prod-issuer\" not found","name":"origin-issuer/controllers/CertificateRequest","certificaterequest":{"Namespace":"istio-system","Name":"raspbernetes-com-zt9wv"},"namespace":"istio-system","name":"prod-issuer","time":"2021-01-12T00:11:13Z","message":"failed to retrieve OriginIssuer resource"}
```

**Comment by terinjokes** [comment]
> however, I've deployed origin-ca-issuer with the OriginIssuer

You probably know this already, but I want to be clear here. `OriginIssuer` and `Certificate` need to be in the same namespace, but that namespace can be different than where you deployed "origin-ca-issuer".

> A feature I'd like to see is to be able to create a cluster scoped `ClusterOriginIssuer` resource that my Certificates can reference.

This is on my todo list.

**Comment by xunholy** [comment]
Yep, I worked that aspect out.

A second question was when using the cert it works fine when I proxy through CloudFlare but using the cert for a split-horizon with internal DNS my machine didn't trust the root CA, I guess this is fine but I'd rather not have to trust the CA on all devices, do you have any thoughts on what would potentially fix this issue?

**Comment by upcFrost** [comment]
>OriginIssuer and Certificate need to be in the same namespace

And the Origin CA token should be in the same namespace as well, which is pretty bad when you're trying to auto-create namespaces for code review

**Comment by diversit** [comment]
Please add support for a cluster-scoped issuer.

**Comment by terinjokes** [comment]
I've started work on this.

**Comment by james-callahan** [comment]
@terinjokes any updates on this one?

**Comment by terinjokes** [comment]
I started writing the code here, but I haven't finished.

**Comment by sgran** [comment]
If you can push it to a branch I can probably find time to help out?

**Comment by pjetr3k** [comment]
any progress on this? or any workaround to not deploy the issuer and secret to every single namespace?

**Comment by bsgrigorov** [comment]
Any updates? This would be very useful for us.

**Comment by Eric-TPS** [comment]
Can we expect this feature anytime soon? I'm planning a buildout and want to set expectations.

**Comment by Kampe** [comment]
This would be wildly useful

**Comment by vaelant** [comment]
Any update on this? To summarize this solution works for a single namespace only. If this were refactored to deploy as a ClusterOriginIssuer then it'd cover an entire Kubernetes cluster and it'd reduce the need for redundant objects. I guarantee you'd see a huge uptick in Kubernetes adoption as a result.

Terin I will buy you a one _whole_ coffee and say nothing but good things about your name from here on out. Apologies for the bump, just anxiously waiting. Thanks for your effort and good luck!

**Comment by oleksandr-shkovyra** [comment]
@terinjokes any updates here? I see that you already started some work here.

**Comment by ManuInNZ** [comment]
Same, I would really like to avoid replicating the secret on every namespace where I want an issuer.

**Comment by penumbra23** [comment]
[My fork](https://github.com/penumbra23/origin-ca-cluster-issuer) changes `OriginIssuer` to `OriginClusterIssuer`, tested on kind and hosted cluster.

Some important things to note:
- apply the newly created CRD
- `serviceKeyRef` has a required `namespace` field to target a secret inside a namespace (can be any namespace)
- `issuer-kind` and `issuer-group` annotations on the Ingress resource are required in order to match the certificate request to the `OriginClusterIssuer`

Any feedback for improvement is welcome!

Btw, great work @terinjokes ! :clap:

**Comment by pimjansen** [comment]
@terinjokes any update on this? And can we get the changes from @penumbra23 for example back on the main stream? I do not really like all the forks all over the place

**Comment by terinjokes** [comment]
I'm still working on it, but this is not my full-time job. I know nothing about changes @penumbra23 has made as they never opened a PR.

**Comment by penumbra23** [comment]
@pimjansen @terinjokes Well, actually my fork changed the whole operator to a cluster issuer, so it's not working anymore as a namespaced issuer. When I got some time I will update the code to have both options available.

**Comment by pimjansen** [comment]
> I'm still working on it, but this is not my full-time job. I know nothing about changes @penumbra23 has made as they never opened a PR.

Understand ofc! For the community it would be great if you could wrap your heads together 👍🏻

**Comment by adamthewilliam** [comment]
If anyone is wondering how to use ClusterOriginIssuer:

```
kubectl apply -f https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/v0.11.0/deploy/crds/cert-manager.k8s.cloudflare.com_clusteroriginissuers.yaml
```

```
helm install oci://ghcr.io/cloudflare/origin-ca-issuer-charts/origin-ca-issuer --version 0.5.11 --namespace cert-manager
```

For extra context, here is what my ClusterOriginIssuer yaml looks like (ignore the terraform):

```
resource "kubectl_manifest" "cloudflare_origin_issuer" {
  provider = kubectl
  depends_on = [ time_sleep.wait_for_crds, null_resource.install_origin_ca_issuer ]
  yaml_body = yamlencode({
    apiVersion  = "cert-manager.k8s.cloudflare.com/v1"
    kind        = "ClusterOriginIssuer"
    metadata    = {
      name      = "cloudflare-origin-issuer"
    }
    spec = {
      requestType = "OriginECC"
      auth = {
        tokenRef = {
          name =  "azkv-cloudflare-origin-ca-key"
          key = "cloudflare-origin-ca-key"
        }
      }    
    }
  })
}
```

**Comment by philthynz** [comment]
For those using ArgoCD, the `oci://` in the Helm repo was causing an issue. My config if your looking to get this working:

Install Cert Manager
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: ingress
  sources:
    - repoURL: "https://charts.jetstack.io"
      chart: cert-manager
      targetRevision: v1.16.2
      helm:
        parameters:
          - name: crds.enabled
            value: "true"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 2m
      limit: 5
    syncOptions:
      - Validate=false
      - CreateNamespace=true
```

Install ingress-nginx

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: ingress
  sources:
    - repoURL: "https://kubernetes.github.io/ingress-nginx"
      chart: ingress-nginx
      targetRevision: 4.12.0-beta.0
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 2m
      limit: 5
    syncOptions:
      - Validate=false
      - CreateNamespace=true
```

Install origin-ca-issuer

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: origin-ca-issuer
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: origin-ca-issuer
  project: ingress
  sources:
    - repoURL: "<your-private-repo>"
      path: apps/ingress/origin_ca_issuer #<-- Path to where additional yaml's are
      targetRevision: HEAD
    - repoURL: "https://github.com/cloudflare/origin-ca-issuer"
      path: deploy/crds #<-- Deploy CRD's
      targetRevision: v0.11.0
    - repoURL: "ghcr.io/cloudflare/origin-ca-issuer-charts" # Use helm repo without "oci://"
      chart: origin-ca-issuer
      targetRevision: 0.5.11
      helm:
        passCredentials: true
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 2m
      limit: 5
    syncOptions:
      - Validate=false
      - CreateNamespace=true
```

kustomize file that will be synced by the first git source:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: origin-ca-issuer
resources:
  - api_secret.yml
  - cluster_issuer.yml
```

api_secret.yml contains the secret for the Cloud Flare API token. I'm using [external-secrets](https://github.com/external-secrets/external-secrets) with oracle cloud vault. External secrets supports multiple back ends. Or just create the secret manually.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cfapi-token
spec:
  refreshInterval: 0.03m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: cfapi-token
    creationPolicy: Owner
  data:
    - secretKey: CloudflareAPIToken
      remoteRef:
        key: CloudflareAPIKey
```

cluster_issuer.yml

```
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: prod-cluster-issuer
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cfapi-token
      key: CloudflareAPIToken
```

Ingress annotation for ArgoCD:

```
    cert-manager.io/issuer: prod-cluster-issuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    cert-manager.io/issuer-kind: ClusterOriginIssuer
```

You may need to port forward the ArgoCD web UI and use `argocd login localhost:35707` with the basic auth admin creds to get these ArgoCD resources deployed. If you don't yet have the ArgoCd ingress working because of the lack of cert.
