### ISSUE TITLE
403 when using origin-ca-issuer

### ISSUE THREAD

**Issue by joaogl** [cloudflare/origin-ca-issuer#54]
Hey!

So, I have a k8s cluster on digital ocean and I'm using origin-ca-issuer to have the certificates from cloudflare on my k8s cluster.
I've set it up but it seems something is failing but I can't quite figure out what and I've ran out of ideas to look into.

Basically I have created my ingress as follows:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: text-ingress
  namespace: default
  annotations:
    # nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "test.stagging.mydomain.com"

    # ssl certificate
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com

    # dns record
    external-dns.alpha.kubernetes.io/hostname: test.stagging.mydomain.com
    external-dns.alpha.kubernetes.io/ttl: "1"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nginx
                port:
                  number: 80
      host: test.stagging.mydomain.com
  tls:
    - hosts:
        - test.stagging.mydomain.com
      secretName: test-stagging-mydomain-com-tls
```

What happens is, if I have on cloudflare proxy enabled I get the typical 403 black/white screen, and if I turn it off it works nicely.
I'm thinking its some issue on the certs as when I check them on my browser they are expired somehow... 
![image](https://user-images.githubusercontent.com/1858551/153910791-d5cd819d-e01d-49c8-b92a-94d1efe46caf.png)

More over, when I check my Certificate and my Orders on my cluster it all seems nice without any errors and it says it's valid.

Any ideas would be greatly appreciated.
