### ISSUE TITLE
Using origin-ca-issuer w/ cert-manager shows invalid certificate

### ISSUE THREAD

**Issue by rarecrumb** [cloudflare/origin-ca-issuer#61]
After installing cert-manager and origin-ca-issuer to the `cert-manager` namespace, I create a cert using annotations on the ingress object:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: origin-issuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    cert-manager.io/issuer-kind: OriginIssuer
```

Logs show:
```
{"level":"debug","verbosity":4,"name":"origin-issuer/controllers/CertificateRequest","certificaterequest":{"Namespace":"my-namespace","Name":"my-cert-request-name-xxxx"},"time":"2022-05-11T00:03:34Z","message":"CertificateRequest is Ready. Ignoring."}
```

My OriginIssuer object status shows:
```yaml
  status:
    conditions:
    - lastTransitionTime: "2022-05-10T23:24:18Z"
      message: OriginIssuer verified and ready to sign certificates
      reason: Verified
      status: "True"
      type: Ready
```

My CertificateRequest object shows:
```yaml
  conditions:
    - lastTransitionTime: '2022-05-10T23:29:34Z'
      message: Certificate request has been approved by cert-manager.io
      reason: cert-manager.io
      status: 'True'
      type: Approved
    - lastTransitionTime: '2022-05-10T23:29:34Z'
      message: Certificate issued
      reason: Issued
      status: 'True'
      type: Ready
```

My Certificate object shows:
```yaml
status:
  conditions:
    - lastTransitionTime: '2022-05-10T23:29:34Z'
      message: Certificate is up to date and has not expired
      observedGeneration: 3
      reason: Ready
      status: 'True'
      type: Ready
```

However, visitng my website or issuing a curl command shows:
```
❯ curl -vvv https://my.domain.com/
*   Trying ip.address.goes.here:443...
* Connected to my.domain.com (ip.address.goes.here) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html
```
